### Obtener todos los diarios
GET http://localhost:2508/diaries

### Obtener todos los diarios de un usuario específico
GET http://localhost:2508/diaries?user_id=6BEJ6uhjjJrdfgLhbeFH

### Obtener un diario por su ID
GET http://localhost:2508/diaries/79dc3d04e6d8413697f0bb5dcff2280e

### Crear un nuevo diario
POST http://localhost:2508/diaries
Content-Type: application/json

{
  "id":"d3b5c0d2-4e4e-49a6-9cfb-12d2a2c4b2b5",
  "title":"pepe",
  "description": "Mi primer diario",
  "date": "2024-04-06",
  "user_id": "b7e9c4cd20ef4d7b9a73f9d7dd72f19e"
}

### Actualizar un diario existente
PUT http://localhost:2508/diaries/Y56zGSJufrI3U24psxlV
Content-Type: application/json

{
  "description": "DiariO actualizado",
  "date": "2024-04-07"
}

### Eliminar un diario por su ID
DELETE http://localhost:2508/diaries/9ZqU6eFgzOQn1xIAP1Hm
