### Obtener todas las tareas
GET http://localhost:2508/tasks
### Obtener todas las tareas
GET http://localhost:2508/tasks?user_id=5yExbJuVC3NLrLVjA0e0

### Obtener una tarea por su ID
GET http://localhost:2508/tasks/fmuDUyscYMN0qyKzmn5y

### Crear una nueva tarea
POST http://localhost:2508/tasks
Content-Type: application/json

{
  "id":"10f5b31b-087d-46e4-908d-518788d33040",
  "title": "Tarea importante",
  "description": "Realizar una tarea importante",
  "completed": false,
  "date": "2024-04-06T10:00:00",
  "category": "Tarea",
  "user_id": "5yExbJuVC3NLrLVjA0e7"
}

### Actualizar una tarea existente
PUT http://localhost:2508/tasks/f47ac10b58cc4372a5670e02b2c3d479
Content-Type: application/json

{
  "date": "2024-04-06T14:00:00"
}

### Eliminar una tarea por su ID
DELETE http://localhost:2508/tasks/f47ac10b58cc4372a5670e02b2c3d479
